# Generated by Django 4.2.11 on 2024-03-22 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_nota'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='nota',
            field=models.CharField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(default='', null=True),
        ),
    ]
